route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 30s
  receiver: scale
  routes:
  - match:
      service: gateway
      receiver: scale
      severity: major

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

receivers:
- name: 'scale'
  webhook_configs:
    - url: 'http://gateway:8080/system/alert'
      send_resolved: false
      http_config:
        basic_auth:
          username: admin
          password_file: /run/secrets/basic-auth-password